#!/usr/bin/env bash
# Install ufw and set up rules on web-01

sudo apt-get update
sudo apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw enable
sudo ufw deny default incoming
sudo ufw allow default outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
