#!/usr/bin/env bash
#  configuring web-02 to be identical to web-01
sudo apt-get update
sudo apt-get install -y nginx
sudo touch /var/www/html/indext.html

echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/err0r404.html /etc/nginx/sites-available/default
sudo service nginx restart
