#!/usr/bin/env bash
# HAproxy installation and configuration

sudo apt-get -y update
sudo apt-get -y install haproxy
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
        balance roundrobin
        server 5724-web-01 35.173.136.163:80 check
        server 5724-web-02 34.228.255.204:80 check

frontend http
        bind *:80
        mode http
        default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
