#!/usr/bin/env bash
#Transfers a file from the client to the server using scp
display_usage() {
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

if [ "$4" ]; then
	display_usage
elif [ "$3" ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
