#!/usr/bin/env bash
#Installs nginx
sudo apt update
sudo apt install nginx -y
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Holberton School" > /etc/nginx/html/indext.html
sudo service nginx start
