#!/usr/bin/env bash
#custom 404 page that conatins the string 'Ceci n'est pas une page'
sudo apt-get update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
sudo touch /var/www/html/error404.html
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html /etc/nginx/sites-available/default
sudo service nginx restart
