#!/usr/bin/env bash
#custom 404 page that conatins the string 'Ceci n'est pas une page'
sudo apt-get update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
sudo touch /var/www/html/error404.html
echo "Holberton School" | sudo tee /var/www/html/index.html

printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html;
        error_page 404 /error404.html;

        server_name _;

        location /redirect_me {
           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
        }
}
" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
